### ISSUE TITLE
Use site language rather than browser language

### ISSUE THREAD

**Issue by dnasir** [micc83/cookie-notice-js#1]
My machine runs using the English locale, but I regularly visit sites that are in other languages as well. Using the browser language will prevent me from getting the correct notice message when visiting a site in another language, because it will always default to English.

Consider using the `lang` attribute value rather than the browser language.

**Comment by micc83** [comment]
That's actually a very good advice. I kinda feel stupid for having not thought about it earlier :sweat_smile: 
I'll implement it and make it the default behaviour asap.
