### ISSUE TITLE
Example in readme has missing commas

### ISSUE THREAD

**Issue by michalzubkowicz** [micc83/cookie-notice-js#4]
Example code doesn't compile in browser. 

`<script>
    new cookieNoticeJS({
    
       // Localizations of the notice message
       'messageLocales': {
         'it': 'Custom localized message'
       },
      
       // Localizations of the dismiss button text
       'buttonLocales': {
         'it': 'Chiudi'
       },
       
       // Position for the cookie-notifier (default=bottom)
       'cookieNoticePosition':'top'
       
       // Shows the "learn more button (default=false)
       'learnMoreLinkEnabled':false
       
       // The href of the learn more link must be applied if (learnMoreLinkEnabled=true) 
       'learnMoreLinkHref':'/learn/more/index.html'
       
       // Text for optional learn more button
       'learnMoreLinkText':{
           'en':'learn more'
       },
       
       // The message will be shown again in X days
       'expiresIn': 30, 
       
       // Dismiss button background color
       'buttonBgColor': '#d35400',  
       
       // Dismiss button text color
       'buttonTextColor': '#fff', 
         
       // Notice background color
       'noticeBgColor': '#000', 
          
       // Notice text color
       'noticeTextColor': '#fff' 
       
       // the lernMoreLink color (default='#009fdd') 
       'linkColor':'#f00'
          
    });
</script>`

**Comment by micc83** [comment]
Fix in 6eff0de926b2ccb8e9b218feae5d5c1adb0320fd
